FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-cpu.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV HF_HOME=/models
ENV TRANSFORMERS_CACHE=/models
ENV DEVICE=cpu
ENV OBSERVER_MODEL=facebook/opt-1.3b
ENV PERFORMER_MODEL=facebook/opt-iml-1.3b

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
